/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as SplatRouteRouteImport } from './routes/$/route'
import { Route as PublicHomeRouteRouteImport } from './routes/_public/home/route'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRouteRoute = SplatRouteRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicHomeRouteRoute = PublicHomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRouteRoute
  '/': typeof PublicRouteRouteWithChildren
  '/home': typeof PublicHomeRouteRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRouteRoute
  '/': typeof PublicRouteRouteWithChildren
  '/home': typeof PublicHomeRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRouteRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/home': typeof PublicHomeRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/home'
  id: '__root__' | '/$' | '/_public' | '/_public/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRouteRoute: typeof SplatRouteRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/home': {
      id: '/_public/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PublicHomeRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicHomeRouteRoute: typeof PublicHomeRouteRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicHomeRouteRoute: PublicHomeRouteRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRouteRoute: SplatRouteRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
