/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as SplatRouteRouteImport } from './routes/$/route'
import { Route as PublicScoreRouteRouteImport } from './routes/_public/score/route'
import { Route as PublicPracticeRouteRouteImport } from './routes/_public/practice/route'
import { Route as PublicHomeRouteRouteImport } from './routes/_public/home/route'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRouteRoute = SplatRouteRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicScoreRouteRoute = PublicScoreRouteRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPracticeRouteRoute = PublicPracticeRouteRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicHomeRouteRoute = PublicHomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRouteRoute
  '/': typeof PublicRouteRouteWithChildren
  '/home': typeof PublicHomeRouteRoute
  '/practice': typeof PublicPracticeRouteRoute
  '/score': typeof PublicScoreRouteRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRouteRoute
  '/': typeof PublicRouteRouteWithChildren
  '/home': typeof PublicHomeRouteRoute
  '/practice': typeof PublicPracticeRouteRoute
  '/score': typeof PublicScoreRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRouteRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/home': typeof PublicHomeRouteRoute
  '/_public/practice': typeof PublicPracticeRouteRoute
  '/_public/score': typeof PublicScoreRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/' | '/home' | '/practice' | '/score'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/home' | '/practice' | '/score'
  id:
    | '__root__'
    | '/$'
    | '/_public'
    | '/_public/home'
    | '/_public/practice'
    | '/_public/score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRouteRoute: typeof SplatRouteRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/score': {
      id: '/_public/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof PublicScoreRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/practice': {
      id: '/_public/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PublicPracticeRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/home': {
      id: '/_public/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PublicHomeRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicHomeRouteRoute: typeof PublicHomeRouteRoute
  PublicPracticeRouteRoute: typeof PublicPracticeRouteRoute
  PublicScoreRouteRoute: typeof PublicScoreRouteRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicHomeRouteRoute: PublicHomeRouteRoute,
  PublicPracticeRouteRoute: PublicPracticeRouteRoute,
  PublicScoreRouteRoute: PublicScoreRouteRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRouteRoute: SplatRouteRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
